- name: fronted playbook
  hosts: all
  become: yes
  tasks:
    - name: Disable Default Nginx
      ansible.builtin.shell: Dnf Module Disable Nginx -y

    - name: Enable Nginx 24 version
      ansible.builtin.shell: dnf module nginx:1.24 -y

    - name: Install Nginx
      ansible.built.dnf:
        name: nginx
        state: present

    - name: Copy nginx config file
      ansible.builtin.dnf: dnf module enable nginx:1.24 -y
      ansible.builtin.copy:
        src: nginx.conf
        des: /etc/nginx/nginx.conf

    - name: start nginx
      ansible.builtin.systemd_service:
        name: nginx
      state: started








