-  name: Add Application User
   ansible.builtin.user:
     name: roboshop


-  name: Delete old Application Directory
   ansible.builtin.file:
     path: /app
     state: absent

- name: Create Application Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download and extract application content
  ansible.builtin.unarchive:
  src: https://roboshop-artifacts.s3.amazonaws.com/fronted-v3.zip
  dest: //usr/share/nginx/html
  remote_src: yes